[package]
name = "pbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Disposable Proxmox LXC workspaces for development"
repository = "https://github.com/kierandrewett/pbox"
readme = "../../README.md"
keywords = ["proxmox", "lxc", "workspace", "cli"]
categories = ["command-line-utilities", "development-tools"]

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[[bin]]
name = "pbox"
path = "src/main.rs"

[dependencies]
pbox-relay = { version = "0.1.8", path = "../pbox-relay" }
anyhow.workspace = true
base64.workspace = true
clap.workspace = true
clap_complete.workspace = true
dirs.workspace = true
hex = "0.4"
pbox-agent-client = { version = "0.1.8", path = "../pbox-agent-client" }
pbox-core = { version = "0.1.8", path = "../pbox-core" }
pbox-crypto = { version = "0.1.8", path = "../pbox-crypto" }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
nix.workspace = true
sha2.workspace = true
time.workspace = true
tokio.workspace = true
vte = "0.15"
vt100 = "0.16.2"
unicode-width = "0.2"
