[package]
name = "pbox-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "pbox-agent"
path = "src/main.rs"

[dependencies]
clap.workspace = true
anyhow.workspace = true
ipnet.workspace = true
pbox-proto = { path = "../pbox-proto" }
pbox-crypto = { path = "../pbox-crypto" }
sha2.workspace = true
nix.workspace = true
tonic.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
[dev-dependencies]
pbox-agent-client = { path = "../pbox-agent-client" }
