[package]
name = "pbox-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Authenticated guest agent for pbox workspaces"
repository.workspace = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[[bin]]
name = "pbox-agent"
path = "src/main.rs"

[dependencies]
serde_json.workspace = true
pbox-relay = { version = "0.1.10", path = "../pbox-relay" }
clap.workspace = true
anyhow.workspace = true
ipnet.workspace = true
pbox-proto = { version = "0.1.10", path = "../pbox-proto" }
pbox-crypto = { version = "0.1.10", path = "../pbox-crypto" }
sha2.workspace = true
nix.workspace = true
tonic.workspace = true
rustls.workspace = true
pem.workspace = true
rustls-pki-types.workspace = true
tokio-rustls.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
vt100 = "0.16.2"
hyper-util.workspace = true
tower = { version = "0.5", features = ["util"] }
pbox-agent-client = { version = "0.1.10", path = "../pbox-agent-client" }
