[package]
name = "pbox-agent-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Authenticated client for the pbox guest agent"
repository.workspace = true

[dependencies]
pbox-relay = { version = "0.1.5", path = "../pbox-relay" }
thiserror.workspace = true
pbox-crypto = { version = "0.1.5", path = "../pbox-crypto" }
pbox-proto = { version = "0.1.5", path = "../pbox-proto" }
tonic.workspace = true
rustls.workspace = true
pem.workspace = true
hyper-util.workspace = true
rustls-pki-types.workspace = true
tokio-rustls.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
